### PR TITLE
feat: Lock Array and Object wrappers for safe multithreading

### PR DESCRIPTION
**Pull request by mrousavy**
Adds locks to array and object wrappers to make multi-threaded access (read or write operations, e.g. `push()` and `pop()`)  safe.

Uses a `recursive_mutex`, might have a small performance impact.

### CODE REVIEW

**Comment by chrfalch** [comment]
I finally got around to read the documentation about concurrency and containers in the C++ standard, and I think we could avoid a lot of the locking in the PR - read more here - I'll try to go through and "mark" methods that we need to be careful about a bit later:

https://en.cppreference.com/w/cpp/container#Thread_safety

**Comment by mrousavy** [comment]
@chrfalch which methods are you talking about? Consider the following code:


```ts
const array = useSharedValue([35, 75234, 385, 357])

const threadA = useWorklet(context1, () => {
  'worklet'
  for (let i = 0; i < array.value.length; i++) {
    console.log(array.value[i])
  }
})

const threadB = useWorklet(context2, () => {
  'worklet'
  while (array.value.length > 0) {
    const item = array.value.pop()
    console.log(item)
  }
})

threadA()
threadB()
```

In threadB we remove all items, and in threadA we iterate through the items with said index.

Without throwing a lock on `pop` and `index`, we would probably encounter issues here.

**Comment by mrousavy** [comment]
Also, check out how `pop()` is implemented: https://github.com/margelo/react-native-worklets-core/blob/a92ff4f275fb24bcdb9cc6db404dc1261fccfa90/cpp/wrappers/WKTJsiArrayWrapper.h#L85-L94

We have three separate operations on our `std::vector`:

1. `_array.size()`
2. `_array.at(..)`
3. `_array.pop_back()`

And for example, after step 1 (`size()`), another Thread might've already popped an item in the meantime, so the step 2 (`at(..)`) call might already be out of bounds.

Unless I'm missing something we need to lock on that entire `pop()` method

**Comment by mrousavy** [comment]
Without the lock PR, I get this error randomly after leaving the app run for a while:

image

**Pull request merged**
