### PR TITLE
fix: refactor whitespace check in createWorklet function

### LINKED ISSUE #144: error: no matching function for call to 'all_of'
/Users/vemarav/Developer/gabit/node_modules/react-native-worklets-core/android/build/headers/rnworklets/react-native-worklets-core/WKTJsiWorklet.h:306:24: error: no matching function for call to 'all_of'

### PR DESCRIPTION
**Pull request by jdnichollsc**
Extracted the lambda function used in the std::all_of call into a separate named function.

Closes #144

### CODE REVIEW

**Comment by spsaucier** [comment]
Fixes the issue for me.

**Comment by jdnichollsc** [comment]
let me know what you think folks, I'm just learning this package! 🫡

**Review by Doko-Demo-Doa — APPROVED** [review]

**Comment by adonaiKasawa** [comment]
I resolved the error with the following code:
you must first include the following headers
#include <algorithm>
#include <cctype> // Include for std::isspace
#include <string>
#include <stdexcept> // Include for std::runtime_error

then look for the line where we find
     bool isCodeEmpty = std::all_of(_code.begin(), _code.end(), std::isspace);

replace you with
     bool isCodeEmpty = std::all_of(_code.begin(), _code.end(), [](unsigned char c) { return std::isspace(c); });

**Review by mrousavy — APPROVED** [review]
looks good, nice work!

**Pull request merged**
